### PR TITLE
Add optional kick reasons

### PR DESCRIPTION
**Pull request by TheReverend403**

### CODE REVIEW

**Comment by matpow2** [comment]
CubeWorldConnection.kick should definitely not take a varg argument. Do the ' '.join in the command itself, and make the reason argument optional in CubeWorldConnection.kick (default None).

**Comment by TheReverend403** [comment]
Like this?

**Comment by matpow2** [comment]
Kick method needs to have this signature, since we want to stay backwards-compatible, and sometimes, you probably don't want to provide a reason in your code.

```
def kick(self, reason=None):
```

**Comment by TheReverend403** [comment]
I'm not too sure about the line break before the formatting arguments, but I *think* this is what you had in mind.

**Comment by matpow2** [comment]
Maybe consider

```
    def kick(self, reason=None):
        postfix = ': %s' % reason if reason is not None else ''
        self.send_chat('You have been kicked%s' % postfix)
        self.server.send_chat('%s has been kicked%s' % (self.name, postfix))
        self.disconnect()
```

:)

**Comment by TheReverend403** [comment]
:thumbsup:

**Pull request merged**
