### PR TITLE
Allow people to use SSL because it's 2015 and all networking software…

### PR DESCRIPTION
**Pull request by TheReverend403**
… should support SSL.

### CODE REVIEW

**Comment by matpow2** [comment]
According to this, ssl_verify should actually be an int?

https://github.com/gawel/irc3/blob/643337481330183bdeb1087cd743d0eb9336c02a/examples/config.ini#L11

I agree though!

**Comment by TheReverend403** [comment]
Apparently not, https://github.com/gawel/irc3/blob/643337481330183bdeb1087cd743d0eb9336c02a/irc3/base.py#L73

**Comment by TheReverend403** [comment]
Wait, you could be right.

**Comment by matpow2** [comment]
Right, it can be False OR an integer or a string ->

https://github.com/gawel/irc3/blob/643337481330183bdeb1087cd743d0eb9336c02a/irc3/base.py#L292

i.e. CERT_NONE / CERT_OPTIONAL / CERT_REQUIRED or "CERT_NONE" / "CERT_OPTIONAL" / "CERT_REQUIRED"

**Comment by TheReverend403** [comment]
How about that?

**Comment by matpow2** [comment]
Thanks for flying with cuwo maintenance. We hope your pull request has been pleasant.

**Pull request merged**
