### PR TITLE
Update run_server.sh

### PR DESCRIPTION
**Pull request by yakuuz**

### CODE REVIEW

**Comment by matpow2** [comment]
Actually, `.` is meant as a replacement for `source`. Did this work for you, though?

**Comment by yakuuz** [comment]
without the '/' 
```
sh run_server.sh
run_server.sh: 6: .: run_pyenv.sh: not found
```
with the / its fine.

**Comment by matpow2** [comment]
Can you try trunk instead? I should have fixed it there.

**Comment by yakuuz** [comment]
sh run_server.sh
```
cuwo server started on Thu Jul 13 20:00:02 2017
Loaded script 'log'
Loaded script 'ddos'
Fatal Python error: Illegal instruction

Thread 0x00007f2c23181700 (most recent call first):
  File "/srv/www/projects/trunk/cuwo/world.py", line 288 in run_gen
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54 in run
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 65 in _worker
  File "/usr/lib/python3.4/threading.py", line 868 in run
  File "/usr/lib/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f2c26fa9700 (most recent call first):
  File "<frozen importlib._bootstrap>", line 321 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1532 in source_to_code
  File "<frozen importlib._bootstrap>", line 1572 in get_code
  File "<frozen importlib._bootstrap>", line 1467 in exec_module
  File "<frozen importlib._bootstrap>", line 1129 in _exec
  File "<frozen importlib._bootstrap>", line 1200 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 2226 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2237 in _find_and_load
  File "/srv/www/projects/trunk/cuwo/server.py", line 585 in load_script
  File "/srv/www/projects/trunk/cuwo/server.py", line 484 in __init__
  File "/srv/www/projects/trunk/cuwo/server.py", line 722 in main
  File "/srv/www/projects/trunk/cuwo/server.py", line 737 in <module>
  File "/usr/lib/python3.4/runpy.py", line 85 in _run_code
  File "/usr/lib/python3.4/runpy.py", line 170 in _run_module_as_main
Illegal instruction

```

**Comment by matpow2** [comment]
Can you test again? I changed it again so it should be fixed.

**Comment by yakuuz** [comment]
sh run_server.sh
cuwo server started on Thu Jul 13 22:49:13 2017
Loaded script 'log'
Loaded script 'ddos'
Fatal Python error: Illegal instruction

Thread 0x00007f7c7afe4700 (most recent call first):
  File "/srv/www/projects/trunk/cuwo/world.py", line 288 in run_gen
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54 in run
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 65 in _worker
  File "/usr/lib/python3.4/threading.py", line 868 in run
  File "/usr/lib/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f7c7eded700 (most recent call first):
  File "/usr/lib/python3.4/sre_compile.py", line 170 in _compile
  File "/usr/lib/python3.4/sre_parse.py", line 381 in _parse_sub
  File "/usr/lib/python3.4/sre_parse.py", line 623 in _parse
  File "/usr/lib/python3.4/sre_compile.py", line 170 in _compile
  File "/srv/www/projects/trunk/scripts/commands.py", line 33 in CommandServer
  File "/srv/www/projects/trunk/scripts/commands.py", line 70 in <module>
  File "<frozen importlib._bootstrap>", line 321 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1471 in exec_module
  File "<frozen importlib._bootstrap>", line 1129 in _exec
  File "<frozen importlib._bootstrap>", line 1200 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 2226 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2237 in _find_and_load
  File "/srv/www/projects/trunk/cuwo/server.py", line 585 in load_script
  File "/srv/www/projects/trunk/cuwo/server.py", line 484 in __init__
  File "/srv/www/projects/trunk/cuwo/serveLoaded script 'commands'
r.py", line 722 in main
  File "/srv/www/projects/trunk/cuwo/server.py", line 737 in <module>
  File "/usr/lib/python3.4/runpy.py", line 85 in _run_code
  File "/usr/lib/python3.4Loaded script 'welcome'
/runpy.py", line 170 in _run_module_as_main
Illegal instruction

**Comment by matpow2** [comment]
Did the server run fine with your own fix?

**Comment by yakuuz** [comment]
Yes but it give me the same error on startup since tgen ^^

that is the latest trunk. (downloaded 3 min ago)
```
sh run_server.sh
cuwo server started on Fri Jul 14 14:01:46 2017
Loaded script 'log'
Loaded script 'ddos'
Fatal Python error: Illegal instruction

Thread 0x00007f64b3dbc700 (most recent call first):
  File "/srv/www/projects/trunk/cuwo/world.py", line 288 in run_gen
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 54 in run
  File "/usr/lib/python3.4/concurrent/futures/thread.py", line 65 in _worker
  File "/usr/lib/python3.4/threading.py", line 868 in run
  File "/usr/lib/python3.4/threading.py", line 920 in _bootstrap_inner
  File "/usr/lib/python3.4/threading.py", line 888 in _bootstrap

Thread 0x00007f64b7be4700 (most recent call first):
  File "<frozen importlib._bootstrap>", line 321 in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1532 in source_to_code
  File "<frozen importlib._bootstrap>", line 1572 in get_code
  File "<frozen importlib._bootstrap>", line 1467 in exec_module
  File "<frozen importlib._bootstrap>", line 1129 in _exec
  File "<frozen importlib._bootstrap>", line 1200 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 2226 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 2237 in _find_and_load
  File "/srv/www/projects/trunk/cuwo/server.py", line 585 in load_script
  File "/srv/www/projects/trunk/cuwo/server.py", line 484 in __init__
  File "/srv/www/projects/trunk/cuwo/server.py", line 727 in main
  File "/srv/www/projects/trunk/cuwo/server.py", line 742 in <module>
  File "/usr/lib/python3.4/runpy.py", line 85 in _run_code
  File "/usr/lib/python3.4/runpy.py", line 170 in _run_module_as_main
Illegal instruction
```

**Comment by matpow2** [comment]
This is probably a stretch, but can I get access to the server in question? You can contact me on Discord at matpow2#3521.

**Comment by matpow2** [comment]
Issue was due to wrong data files.

**Pull request closed without merging**
